from . import content_create_update_view
from . import content_delete_view
from . import content_order_view
from . import course_create_view
from . import course_delete_view
from . import course_detail_view
from . import course_list_view
from . import course_module_update_view
from . import course_update_view
from . import manage_course
from . import manage_course_list_view
from . import module_content_list_view
from . import module_order_view
